export const modal = () => {
  const contenedorPadre = document.createElement('div');
  contenedorPadre.setAttribute('class', 'contmodal');
  contenedorPadre.setAttribute('id', 'contmodal');
  const contenedorModal = document.createElement('div');
  contenedorModal.setAttribute('class', 'modal1');
  contenedorModal.setAttribute('id', 'modal');
  const iconomal = document.createElement('IMG');
  iconomal.src = './images/tachecito.png';
  iconomal.setAttribute('id', 'iconomal');
  iconomal.setAttribute('alt', 'incorrecto');
  const mensajemal = document.createElement('h1');
  mensajemal.setAttribute('class', 'mensajemal');
  mensajemal.setAttribute('id', 'mensajemal');
  mensajemal.textContent = 'Verifica tu información';
  const btnVolver = document.createElement('button');
  btnVolver.setAttribute('id', 'botonVolver');
  btnVolver.setAttribute('class', 'botones');
  const cerrarModal = document.createElement('a');
  cerrarModal.textContent = 'Volver';
  cerrarModal.setAttribute('href', '/');
  contenedorModal.append(iconomal, mensajemal, btnVolver);
  const btnMostrarModal = document.createElement('button');
  const mostrarModal = document.createElement('a');
  mostrarModal.textContent = 'Ver';
  mostrarModal.setAttribute('href', '#contmodal');
  btnVolver.appendChild(cerrarModal);
  btnMostrarModal.appendChild(mostrarModal);
  contenedorModal.append(iconomal, mensajemal, btnVolver);
  contenedorPadre.appendChild(contenedorModal);
  return contenedorPadre;
};
